; Auto-generated. Do not edit!


(cl:in-package fanuc_kinematics-msg)


;//! \htmlinclude IKGoal.msg.html

(cl:defclass <IKGoal> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass IKGoal (<IKGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <IKGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'IKGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fanuc_kinematics-msg:<IKGoal> is deprecated: use fanuc_kinematics-msg:IKGoal instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <IKGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fanuc_kinematics-msg:pose-val is deprecated.  Use fanuc_kinematics-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <IKGoal>) ostream)
  "Serializes a message object of type '<IKGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <IKGoal>) istream)
  "Deserializes a message object of type '<IKGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<IKGoal>)))
  "Returns string type for a message object of type '<IKGoal>"
  "fanuc_kinematics/IKGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'IKGoal)))
  "Returns string type for a message object of type 'IKGoal"
  "fanuc_kinematics/IKGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<IKGoal>)))
  "Returns md5sum for a message object of type '<IKGoal>"
  "f192399f711a48924df9a394d37edd67")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'IKGoal)))
  "Returns md5sum for a message object of type 'IKGoal"
  "f192399f711a48924df9a394d37edd67")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<IKGoal>)))
  "Returns full string definition for message of type '<IKGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition. The pose for which we wantto find the inverse kinematics solutions~%geometry_msgs/Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'IKGoal)))
  "Returns full string definition for message of type 'IKGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition. The pose for which we wantto find the inverse kinematics solutions~%geometry_msgs/Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <IKGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <IKGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'IKGoal
    (cl:cons ':pose (pose msg))
))
