// Generated by gencpp from file fanuc_kinematics/ForwardKinematicsResponse.msg
// DO NOT EDIT!


#ifndef FANUC_KINEMATICS_MESSAGE_FORWARDKINEMATICSRESPONSE_H
#define FANUC_KINEMATICS_MESSAGE_FORWARDKINEMATICSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fanuc_kinematics
{
template <class ContainerAllocator>
struct ForwardKinematicsResponse_
{
  typedef ForwardKinematicsResponse_<ContainerAllocator> Type;

  ForwardKinematicsResponse_()
    : translation()
    , rotation()  {
    }
  ForwardKinematicsResponse_(const ContainerAllocator& _alloc)
    : translation(_alloc)
    , rotation(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _translation_type;
  _translation_type translation;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _rotation_type;
  _rotation_type rotation;





  typedef boost::shared_ptr< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ForwardKinematicsResponse_

typedef ::fanuc_kinematics::ForwardKinematicsResponse_<std::allocator<void> > ForwardKinematicsResponse;

typedef boost::shared_ptr< ::fanuc_kinematics::ForwardKinematicsResponse > ForwardKinematicsResponsePtr;
typedef boost::shared_ptr< ::fanuc_kinematics::ForwardKinematicsResponse const> ForwardKinematicsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.translation == rhs.translation &&
    lhs.rotation == rhs.rotation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fanuc_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5b80608aa0b7f5b05ca5427bd9f1fd8";
  }

  static const char* value(const ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5b80608aa0b7f5bULL;
  static const uint64_t static_value2 = 0x05ca5427bd9f1fd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fanuc_kinematics/ForwardKinematicsResponse";
  }

  static const char* value(const ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] translation\n"
"float32[] rotation\n"
"\n"
;
  }

  static const char* value(const ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.translation);
      stream.next(m.rotation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForwardKinematicsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fanuc_kinematics::ForwardKinematicsResponse_<ContainerAllocator>& v)
  {
    s << indent << "translation[]" << std::endl;
    for (size_t i = 0; i < v.translation.size(); ++i)
    {
      s << indent << "  translation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.translation[i]);
    }
    s << indent << "rotation[]" << std::endl;
    for (size_t i = 0; i < v.rotation.size(); ++i)
    {
      s << indent << "  rotation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rotation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FANUC_KINEMATICS_MESSAGE_FORWARDKINEMATICSRESPONSE_H
