// Generated by gencpp from file fanuc_kinematics/ForwardKinematicsRequest.msg
// DO NOT EDIT!


#ifndef FANUC_KINEMATICS_MESSAGE_FORWARDKINEMATICSREQUEST_H
#define FANUC_KINEMATICS_MESSAGE_FORWARDKINEMATICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fanuc_kinematics
{
template <class ContainerAllocator>
struct ForwardKinematicsRequest_
{
  typedef ForwardKinematicsRequest_<ContainerAllocator> Type;

  ForwardKinematicsRequest_()
    : link_name()  {
    }
  ForwardKinematicsRequest_(const ContainerAllocator& _alloc)
    : link_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _link_name_type;
  _link_name_type link_name;





  typedef boost::shared_ptr< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ForwardKinematicsRequest_

typedef ::fanuc_kinematics::ForwardKinematicsRequest_<std::allocator<void> > ForwardKinematicsRequest;

typedef boost::shared_ptr< ::fanuc_kinematics::ForwardKinematicsRequest > ForwardKinematicsRequestPtr;
typedef boost::shared_ptr< ::fanuc_kinematics::ForwardKinematicsRequest const> ForwardKinematicsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.link_name == rhs.link_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fanuc_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d82d60381f1b66a30f2157f60884345";
  }

  static const char* value(const ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d82d60381f1b66aULL;
  static const uint64_t static_value2 = 0x30f2157f60884345ULL;
};

template<class ContainerAllocator>
struct DataType< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fanuc_kinematics/ForwardKinematicsRequest";
  }

  static const char* value(const ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string link_name\n"
;
  }

  static const char* value(const ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForwardKinematicsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fanuc_kinematics::ForwardKinematicsRequest_<ContainerAllocator>& v)
  {
    s << indent << "link_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.link_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FANUC_KINEMATICS_MESSAGE_FORWARDKINEMATICSREQUEST_H
