// Generated by gencpp from file fanuc_kinematics/ForwardKinematics.msg
// DO NOT EDIT!


#ifndef FANUC_KINEMATICS_MESSAGE_FORWARDKINEMATICS_H
#define FANUC_KINEMATICS_MESSAGE_FORWARDKINEMATICS_H

#include <ros/service_traits.h>


#include <fanuc_kinematics/ForwardKinematicsRequest.h>
#include <fanuc_kinematics/ForwardKinematicsResponse.h>


namespace fanuc_kinematics
{

struct ForwardKinematics
{

typedef ForwardKinematicsRequest Request;
typedef ForwardKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ForwardKinematics
} // namespace fanuc_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fanuc_kinematics::ForwardKinematics > {
  static const char* value()
  {
    return "7878278dc9e10f5c8ed44003c357b811";
  }

  static const char* value(const ::fanuc_kinematics::ForwardKinematics&) { return value(); }
};

template<>
struct DataType< ::fanuc_kinematics::ForwardKinematics > {
  static const char* value()
  {
    return "fanuc_kinematics/ForwardKinematics";
  }

  static const char* value(const ::fanuc_kinematics::ForwardKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::fanuc_kinematics::ForwardKinematicsRequest> should match
// service_traits::MD5Sum< ::fanuc_kinematics::ForwardKinematics >
template<>
struct MD5Sum< ::fanuc_kinematics::ForwardKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fanuc_kinematics::ForwardKinematics >::value();
  }
  static const char* value(const ::fanuc_kinematics::ForwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fanuc_kinematics::ForwardKinematicsRequest> should match
// service_traits::DataType< ::fanuc_kinematics::ForwardKinematics >
template<>
struct DataType< ::fanuc_kinematics::ForwardKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::fanuc_kinematics::ForwardKinematics >::value();
  }
  static const char* value(const ::fanuc_kinematics::ForwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fanuc_kinematics::ForwardKinematicsResponse> should match
// service_traits::MD5Sum< ::fanuc_kinematics::ForwardKinematics >
template<>
struct MD5Sum< ::fanuc_kinematics::ForwardKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fanuc_kinematics::ForwardKinematics >::value();
  }
  static const char* value(const ::fanuc_kinematics::ForwardKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fanuc_kinematics::ForwardKinematicsResponse> should match
// service_traits::DataType< ::fanuc_kinematics::ForwardKinematics >
template<>
struct DataType< ::fanuc_kinematics::ForwardKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::fanuc_kinematics::ForwardKinematics >::value();
  }
  static const char* value(const ::fanuc_kinematics::ForwardKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FANUC_KINEMATICS_MESSAGE_FORWARDKINEMATICS_H
