// Generated by gencpp from file fanuc_kinematics/IKGoal.msg
// DO NOT EDIT!


#ifndef FANUC_KINEMATICS_MESSAGE_IKGOAL_H
#define FANUC_KINEMATICS_MESSAGE_IKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace fanuc_kinematics
{
template <class ContainerAllocator>
struct IKGoal_
{
  typedef IKGoal_<ContainerAllocator> Type;

  IKGoal_()
    : pose()  {
    }
  IKGoal_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::fanuc_kinematics::IKGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fanuc_kinematics::IKGoal_<ContainerAllocator> const> ConstPtr;

}; // struct IKGoal_

typedef ::fanuc_kinematics::IKGoal_<std::allocator<void> > IKGoal;

typedef boost::shared_ptr< ::fanuc_kinematics::IKGoal > IKGoalPtr;
typedef boost::shared_ptr< ::fanuc_kinematics::IKGoal const> IKGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fanuc_kinematics::IKGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fanuc_kinematics::IKGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fanuc_kinematics::IKGoal_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::IKGoal_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fanuc_kinematics::IKGoal_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::IKGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fanuc_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::IKGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::IKGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::IKGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::IKGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::IKGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::IKGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fanuc_kinematics::IKGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::fanuc_kinematics::IKGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf192399f711a4892ULL;
  static const uint64_t static_value2 = 0x4df9a394d37edd67ULL;
};

template<class ContainerAllocator>
struct DataType< ::fanuc_kinematics::IKGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fanuc_kinematics/IKGoal";
  }

  static const char* value(const ::fanuc_kinematics::IKGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fanuc_kinematics::IKGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition. The pose for which we wantto find the inverse kinematics solutions\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::fanuc_kinematics::IKGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fanuc_kinematics::IKGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IKGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fanuc_kinematics::IKGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fanuc_kinematics::IKGoal_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FANUC_KINEMATICS_MESSAGE_IKGOAL_H
