// Generated by gencpp from file fanuc_kinematics/JointAnglesArray.msg
// DO NOT EDIT!


#ifndef FANUC_KINEMATICS_MESSAGE_JOINTANGLESARRAY_H
#define FANUC_KINEMATICS_MESSAGE_JOINTANGLESARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fanuc_kinematics/JointAngles.h>

namespace fanuc_kinematics
{
template <class ContainerAllocator>
struct JointAnglesArray_
{
  typedef JointAnglesArray_<ContainerAllocator> Type;

  JointAnglesArray_()
    : array()  {
    }
  JointAnglesArray_(const ContainerAllocator& _alloc)
    : array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::fanuc_kinematics::JointAngles_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >::other >  _array_type;
  _array_type array;





  typedef boost::shared_ptr< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> const> ConstPtr;

}; // struct JointAnglesArray_

typedef ::fanuc_kinematics::JointAnglesArray_<std::allocator<void> > JointAnglesArray;

typedef boost::shared_ptr< ::fanuc_kinematics::JointAnglesArray > JointAnglesArrayPtr;
typedef boost::shared_ptr< ::fanuc_kinematics::JointAnglesArray const> JointAnglesArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator2> & rhs)
{
  return lhs.array == rhs.array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fanuc_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23f8d77e3668a9f9844ada86c754258b";
  }

  static const char* value(const ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23f8d77e3668a9f9ULL;
  static const uint64_t static_value2 = 0x844ada86c754258bULL;
};

template<class ContainerAllocator>
struct DataType< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fanuc_kinematics/JointAnglesArray";
  }

  static const char* value(const ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represent an array of a joint angles' set.\n"
"JointAngles[] array\n"
"================================================================================\n"
"MSG: fanuc_kinematics/JointAngles\n"
"# Represent a set of joint angles\n"
"float64[] joint_angles\n"
;
  }

  static const char* value(const ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointAnglesArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fanuc_kinematics::JointAnglesArray_<ContainerAllocator>& v)
  {
    s << indent << "array[]" << std::endl;
    for (size_t i = 0; i < v.array.size(); ++i)
    {
      s << indent << "  array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >::stream(s, indent + "    ", v.array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FANUC_KINEMATICS_MESSAGE_JOINTANGLESARRAY_H
