// Generated by gencpp from file fanuc_kinematics/JointAngles.msg
// DO NOT EDIT!


#ifndef FANUC_KINEMATICS_MESSAGE_JOINTANGLES_H
#define FANUC_KINEMATICS_MESSAGE_JOINTANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fanuc_kinematics
{
template <class ContainerAllocator>
struct JointAngles_
{
  typedef JointAngles_<ContainerAllocator> Type;

  JointAngles_()
    : joint_angles()  {
    }
  JointAngles_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_angles_type;
  _joint_angles_type joint_angles;





  typedef boost::shared_ptr< ::fanuc_kinematics::JointAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fanuc_kinematics::JointAngles_<ContainerAllocator> const> ConstPtr;

}; // struct JointAngles_

typedef ::fanuc_kinematics::JointAngles_<std::allocator<void> > JointAngles;

typedef boost::shared_ptr< ::fanuc_kinematics::JointAngles > JointAnglesPtr;
typedef boost::shared_ptr< ::fanuc_kinematics::JointAngles const> JointAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fanuc_kinematics::JointAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fanuc_kinematics::JointAngles_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::JointAngles_<ContainerAllocator2> & rhs)
{
  return lhs.joint_angles == rhs.joint_angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fanuc_kinematics::JointAngles_<ContainerAllocator1> & lhs, const ::fanuc_kinematics::JointAngles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fanuc_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fanuc_kinematics::JointAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_kinematics::JointAngles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_kinematics::JointAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eebf9cc7d525d143ad033b65dacb648";
  }

  static const char* value(const ::fanuc_kinematics::JointAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eebf9cc7d525d14ULL;
  static const uint64_t static_value2 = 0x3ad033b65dacb648ULL;
};

template<class ContainerAllocator>
struct DataType< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fanuc_kinematics/JointAngles";
  }

  static const char* value(const ::fanuc_kinematics::JointAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represent a set of joint angles\n"
"float64[] joint_angles\n"
;
  }

  static const char* value(const ::fanuc_kinematics::JointAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fanuc_kinematics::JointAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fanuc_kinematics::JointAngles_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FANUC_KINEMATICS_MESSAGE_JOINTANGLES_H
