// Generated by gencpp from file fanuc_moveit/Transformations.msg
// DO NOT EDIT!


#ifndef FANUC_MOVEIT_MESSAGE_TRANSFORMATIONS_H
#define FANUC_MOVEIT_MESSAGE_TRANSFORMATIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <fanuc_moveit/AxisAngle.h>
#include <fanuc_moveit/TransformationMatrix.h>

namespace fanuc_moveit
{
template <class ContainerAllocator>
struct Transformations_
{
  typedef Transformations_<ContainerAllocator> Type;

  Transformations_()
    : parent_frame()
    , child_frame()
    , translation()
    , rpy()
    , axis_angle()
    , tf_matrix()  {
    }
  Transformations_(const ContainerAllocator& _alloc)
    : parent_frame(_alloc)
    , child_frame(_alloc)
    , translation(_alloc)
    , rpy(_alloc)
    , axis_angle(_alloc)
    , tf_matrix(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _parent_frame_type;
  _parent_frame_type parent_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _child_frame_type;
  _child_frame_type child_frame;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _translation_type;
  _translation_type translation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rpy_type;
  _rpy_type rpy;

   typedef  ::fanuc_moveit::AxisAngle_<ContainerAllocator>  _axis_angle_type;
  _axis_angle_type axis_angle;

   typedef  ::fanuc_moveit::TransformationMatrix_<ContainerAllocator>  _tf_matrix_type;
  _tf_matrix_type tf_matrix;





  typedef boost::shared_ptr< ::fanuc_moveit::Transformations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fanuc_moveit::Transformations_<ContainerAllocator> const> ConstPtr;

}; // struct Transformations_

typedef ::fanuc_moveit::Transformations_<std::allocator<void> > Transformations;

typedef boost::shared_ptr< ::fanuc_moveit::Transformations > TransformationsPtr;
typedef boost::shared_ptr< ::fanuc_moveit::Transformations const> TransformationsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fanuc_moveit::Transformations_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fanuc_moveit::Transformations_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fanuc_moveit::Transformations_<ContainerAllocator1> & lhs, const ::fanuc_moveit::Transformations_<ContainerAllocator2> & rhs)
{
  return lhs.parent_frame == rhs.parent_frame &&
    lhs.child_frame == rhs.child_frame &&
    lhs.translation == rhs.translation &&
    lhs.rpy == rhs.rpy &&
    lhs.axis_angle == rhs.axis_angle &&
    lhs.tf_matrix == rhs.tf_matrix;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fanuc_moveit::Transformations_<ContainerAllocator1> & lhs, const ::fanuc_moveit::Transformations_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fanuc_moveit

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fanuc_moveit::Transformations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fanuc_moveit::Transformations_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_moveit::Transformations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_moveit::Transformations_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_moveit::Transformations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_moveit::Transformations_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fanuc_moveit::Transformations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbbf0fb7520bc61fcd2744d84e1d226c";
  }

  static const char* value(const ::fanuc_moveit::Transformations_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbbf0fb7520bc61fULL;
  static const uint64_t static_value2 = 0xcd2744d84e1d226cULL;
};

template<class ContainerAllocator>
struct DataType< ::fanuc_moveit::Transformations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fanuc_moveit/Transformations";
  }

  static const char* value(const ::fanuc_moveit::Transformations_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fanuc_moveit::Transformations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#This represent three different representation of a trasform, \n"
"#RPY, axis-angle and homogeneus trasformation matrix\n"
"string parent_frame\n"
"string child_frame\n"
"geometry_msgs/Vector3 translation\n"
"geometry_msgs/Vector3 rpy\n"
"AxisAngle axis_angle\n"
"TransformationMatrix tf_matrix\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: fanuc_moveit/AxisAngle\n"
"#This represent a transformation as axis-angle representation\n"
"\n"
"geometry_msgs/Vector3 axis\n"
"float32 angle\n"
"\n"
"================================================================================\n"
"MSG: fanuc_moveit/TransformationMatrix\n"
"# This represent the 4x4 trasformation matrix, see MultiArrayLayout\n"
"#message definition for documentation on all multiarrays.\n"
"\n"
"geometry_msgs/Vector3 translation\n"
"float32[] rotation\n"
;
  }

  static const char* value(const ::fanuc_moveit::Transformations_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fanuc_moveit::Transformations_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parent_frame);
      stream.next(m.child_frame);
      stream.next(m.translation);
      stream.next(m.rpy);
      stream.next(m.axis_angle);
      stream.next(m.tf_matrix);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Transformations_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fanuc_moveit::Transformations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fanuc_moveit::Transformations_<ContainerAllocator>& v)
  {
    s << indent << "parent_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.parent_frame);
    s << indent << "child_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.child_frame);
    s << indent << "translation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.translation);
    s << indent << "rpy: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy);
    s << indent << "axis_angle: ";
    s << std::endl;
    Printer< ::fanuc_moveit::AxisAngle_<ContainerAllocator> >::stream(s, indent + "  ", v.axis_angle);
    s << indent << "tf_matrix: ";
    s << std::endl;
    Printer< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >::stream(s, indent + "  ", v.tf_matrix);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FANUC_MOVEIT_MESSAGE_TRANSFORMATIONS_H
