// Generated by gencpp from file fanuc_moveit/TransformationMatrix.msg
// DO NOT EDIT!


#ifndef FANUC_MOVEIT_MESSAGE_TRANSFORMATIONMATRIX_H
#define FANUC_MOVEIT_MESSAGE_TRANSFORMATIONMATRIX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace fanuc_moveit
{
template <class ContainerAllocator>
struct TransformationMatrix_
{
  typedef TransformationMatrix_<ContainerAllocator> Type;

  TransformationMatrix_()
    : translation()
    , rotation()  {
    }
  TransformationMatrix_(const ContainerAllocator& _alloc)
    : translation(_alloc)
    , rotation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _translation_type;
  _translation_type translation;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _rotation_type;
  _rotation_type rotation;





  typedef boost::shared_ptr< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> const> ConstPtr;

}; // struct TransformationMatrix_

typedef ::fanuc_moveit::TransformationMatrix_<std::allocator<void> > TransformationMatrix;

typedef boost::shared_ptr< ::fanuc_moveit::TransformationMatrix > TransformationMatrixPtr;
typedef boost::shared_ptr< ::fanuc_moveit::TransformationMatrix const> TransformationMatrixConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fanuc_moveit::TransformationMatrix_<ContainerAllocator1> & lhs, const ::fanuc_moveit::TransformationMatrix_<ContainerAllocator2> & rhs)
{
  return lhs.translation == rhs.translation &&
    lhs.rotation == rhs.rotation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fanuc_moveit::TransformationMatrix_<ContainerAllocator1> & lhs, const ::fanuc_moveit::TransformationMatrix_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fanuc_moveit

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbb3991bb5188e46c0240cb0698b70c8";
  }

  static const char* value(const ::fanuc_moveit::TransformationMatrix_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbb3991bb5188e46ULL;
  static const uint64_t static_value2 = 0xc0240cb0698b70c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fanuc_moveit/TransformationMatrix";
  }

  static const char* value(const ::fanuc_moveit::TransformationMatrix_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represent the 4x4 trasformation matrix, see MultiArrayLayout\n"
"#message definition for documentation on all multiarrays.\n"
"\n"
"geometry_msgs/Vector3 translation\n"
"float32[] rotation\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::fanuc_moveit::TransformationMatrix_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.translation);
      stream.next(m.rotation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransformationMatrix_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fanuc_moveit::TransformationMatrix_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fanuc_moveit::TransformationMatrix_<ContainerAllocator>& v)
  {
    s << indent << "translation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.translation);
    s << indent << "rotation[]" << std::endl;
    for (size_t i = 0; i < v.rotation.size(); ++i)
    {
      s << indent << "  rotation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rotation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FANUC_MOVEIT_MESSAGE_TRANSFORMATIONMATRIX_H
