// Generated by gencpp from file moveit_dp_redundancy_resolution_msgs/GetOptimizedJointsTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef MOVEIT_DP_REDUNDANCY_RESOLUTION_MSGS_MESSAGE_GETOPTIMIZEDJOINTSTRAJECTORYRESPONSE_H
#define MOVEIT_DP_REDUNDANCY_RESOLUTION_MSGS_MESSAGE_GETOPTIMIZEDJOINTSTRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <moveit_msgs/RobotTrajectory.h>
#include <moveit_msgs/MoveItErrorCodes.h>

namespace moveit_dp_redundancy_resolution_msgs
{
template <class ContainerAllocator>
struct GetOptimizedJointsTrajectoryResponse_
{
  typedef GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> Type;

  GetOptimizedJointsTrajectoryResponse_()
    : solution()
    , error_code()  {
    }
  GetOptimizedJointsTrajectoryResponse_(const ContainerAllocator& _alloc)
    : solution(_alloc)
    , error_code(_alloc)  {
  (void)_alloc;
    }



   typedef  ::moveit_msgs::RobotTrajectory_<ContainerAllocator>  _solution_type;
  _solution_type solution;

   typedef  ::moveit_msgs::MoveItErrorCodes_<ContainerAllocator>  _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetOptimizedJointsTrajectoryResponse_

typedef ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<std::allocator<void> > GetOptimizedJointsTrajectoryResponse;

typedef boost::shared_ptr< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse > GetOptimizedJointsTrajectoryResponsePtr;
typedef boost::shared_ptr< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse const> GetOptimizedJointsTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator1> & lhs, const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.solution == rhs.solution &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator1> & lhs, const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moveit_dp_redundancy_resolution_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccad629f9156e380c5ac7b18f3aa07e1";
  }

  static const char* value(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccad629f9156e380ULL;
  static const uint64_t static_value2 = 0xc5ac7b18f3aa07e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveit_dp_redundancy_resolution_msgs/GetOptimizedJointsTrajectoryResponse";
  }

  static const char* value(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# The computed solution trajectory, for the desired group, in configuration space\n"
"moveit_msgs/RobotTrajectory solution\n"
"\n"
"# The error code of the computation\n"
"moveit_msgs/MoveItErrorCodes error_code\n"
"\n"
"\n"
"================================================================================\n"
"MSG: moveit_msgs/RobotTrajectory\n"
"trajectory_msgs/JointTrajectory joint_trajectory\n"
"trajectory_msgs/MultiDOFJointTrajectory multi_dof_joint_trajectory\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/MultiDOFJointTrajectory\n"
"# The header is used to specify the coordinate frame and the reference time for the trajectory durations\n"
"Header header\n"
"\n"
"# A representation of a multi-dof joint trajectory (each point is a transformation)\n"
"# Each point along the trajectory will include an array of positions/velocities/accelerations\n"
"# that has the same length as the array of joint names, and has the same order of joints as \n"
"# the joint names array.\n"
"\n"
"string[] joint_names\n"
"MultiDOFJointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/MultiDOFJointTrajectoryPoint\n"
"# Each multi-dof joint can specify a transform (up to 6 DOF)\n"
"geometry_msgs/Transform[] transforms\n"
"\n"
"# There can be a velocity specified for the origin of the joint \n"
"geometry_msgs/Twist[] velocities\n"
"\n"
"# There can be an acceleration specified for the origin of the joint \n"
"geometry_msgs/Twist[] accelerations\n"
"\n"
"duration time_from_start\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: moveit_msgs/MoveItErrorCodes\n"
"int32 val\n"
"\n"
"# overall behavior\n"
"int32 SUCCESS=1\n"
"int32 FAILURE=99999\n"
"\n"
"int32 PLANNING_FAILED=-1\n"
"int32 INVALID_MOTION_PLAN=-2\n"
"int32 MOTION_PLAN_INVALIDATED_BY_ENVIRONMENT_CHANGE=-3\n"
"int32 CONTROL_FAILED=-4\n"
"int32 UNABLE_TO_AQUIRE_SENSOR_DATA=-5\n"
"int32 TIMED_OUT=-6\n"
"int32 PREEMPTED=-7\n"
"\n"
"# planning & kinematics request errors\n"
"int32 START_STATE_IN_COLLISION=-10\n"
"int32 START_STATE_VIOLATES_PATH_CONSTRAINTS=-11\n"
"\n"
"int32 GOAL_IN_COLLISION=-12\n"
"int32 GOAL_VIOLATES_PATH_CONSTRAINTS=-13\n"
"int32 GOAL_CONSTRAINTS_VIOLATED=-14\n"
"\n"
"int32 INVALID_GROUP_NAME=-15\n"
"int32 INVALID_GOAL_CONSTRAINTS=-16\n"
"int32 INVALID_ROBOT_STATE=-17\n"
"int32 INVALID_LINK_NAME=-18\n"
"int32 INVALID_OBJECT_NAME=-19\n"
"\n"
"# system errors\n"
"int32 FRAME_TRANSFORM_FAILURE=-21\n"
"int32 COLLISION_CHECKING_UNAVAILABLE=-22\n"
"int32 ROBOT_STATE_STALE=-23\n"
"int32 SENSOR_INFO_STALE=-24\n"
"int32 COMMUNICATION_FAILURE=-25\n"
"\n"
"# kinematics errors\n"
"int32 NO_IK_SOLUTION=-31\n"
;
  }

  static const char* value(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.solution);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetOptimizedJointsTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "solution: ";
    s << std::endl;
    Printer< ::moveit_msgs::RobotTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.solution);
    s << indent << "error_code: ";
    s << std::endl;
    Printer< ::moveit_msgs::MoveItErrorCodes_<ContainerAllocator> >::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_DP_REDUNDANCY_RESOLUTION_MSGS_MESSAGE_GETOPTIMIZEDJOINTSTRAJECTORYRESPONSE_H
