// Generated by gencpp from file moveit_dp_redundancy_resolution_msgs/GetOptimizedJointsTrajectory.msg
// DO NOT EDIT!


#ifndef MOVEIT_DP_REDUNDANCY_RESOLUTION_MSGS_MESSAGE_GETOPTIMIZEDJOINTSTRAJECTORY_H
#define MOVEIT_DP_REDUNDANCY_RESOLUTION_MSGS_MESSAGE_GETOPTIMIZEDJOINTSTRAJECTORY_H

#include <ros/service_traits.h>


#include <moveit_dp_redundancy_resolution_msgs/GetOptimizedJointsTrajectoryRequest.h>
#include <moveit_dp_redundancy_resolution_msgs/GetOptimizedJointsTrajectoryResponse.h>


namespace moveit_dp_redundancy_resolution_msgs
{

struct GetOptimizedJointsTrajectory
{

typedef GetOptimizedJointsTrajectoryRequest Request;
typedef GetOptimizedJointsTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetOptimizedJointsTrajectory
} // namespace moveit_dp_redundancy_resolution_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory > {
  static const char* value()
  {
    return "b7de85a4df1e100e5f0aa67c24c62f63";
  }

  static const char* value(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory&) { return value(); }
};

template<>
struct DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory > {
  static const char* value()
  {
    return "moveit_dp_redundancy_resolution_msgs/GetOptimizedJointsTrajectory";
  }

  static const char* value(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryRequest> should match
// service_traits::MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory >
template<>
struct MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory >::value();
  }
  static const char* value(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryRequest> should match
// service_traits::DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory >
template<>
struct DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory >::value();
  }
  static const char* value(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse> should match
// service_traits::MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory >
template<>
struct MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory >::value();
  }
  static const char* value(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse> should match
// service_traits::DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory >
template<>
struct DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectory >::value();
  }
  static const char* value(const ::moveit_dp_redundancy_resolution_msgs::GetOptimizedJointsTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_DP_REDUNDANCY_RESOLUTION_MSGS_MESSAGE_GETOPTIMIZEDJOINTSTRAJECTORY_H
