(cl:defpackage fanuc_moveit-msg
  (:use )
  (:export
   "<AXISANGLE>"
   "AXISANGLE"
   "<AXISANGLE>"
   "AXISANGLE"
   "<TRANSFORMATIONMATRIX>"
   "TRANSFORMATIONMATRIX"
   "<TRANSFORMATIONMATRIX>"
   "TRANSFORMATIONMATRIX"
   "<TRANSFORMATIONS>"
   "TRANSFORMATIONS"
   "<TRANSFORMATIONS>"
   "TRANSFORMATIONS"
   "<TRANSFORMATIONSARRAY>"
   "TRANSFORMATIONSARRAY"
   "<TRANSFORMATIONSARRAY>"
   "TRANSFORMATIONSARRAY"
  ))

