(cl:defpackage moveit_dp_redundancy_resolution_msgs-srv
  (:use )
  (:export
   "GETOPTIMIZEDJOINTSTRAJECTORY"
   "<GETOPTIMIZEDJOINTSTRAJECTORY-REQUEST>"
   "GETOPTIMIZEDJOINTSTRAJECTORY-REQUEST"
   "<GETOPTIMIZEDJOINTSTRAJECTORY-RESPONSE>"
   "GETOPTIMIZEDJOINTSTRAJECTORY-RESPONSE"
  ))

